configuration:
  page_title: "Trellis"
  page_title_suffix: ""
  enable_spa: true
  enable_popovers: true
  locale: "en-US"
  base_url: null
  ignore_patterns:
    - "private"
    - "templates"
    - ".obsidian"
  default_date_type: modified
  theme:
    font_origin: "googleFonts"
    cdn_caching: true
    typography:
      header: "Schibsted Grotesk"
      body: "Source Sans Pro"
      code: "IBM Plex Mono"
    colors:
      light_mode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
        text_highlight: "#fff23688"
      dark_mode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
        text_highlight: "#b3aa0288"

plugins:
  resources:
    css: []
    js: []
    additional_head: []

layout:
  footer:
    links:
  explorer:
    title: "Xplorer"
    folder_default_state: "collapsed"
    folder_click_behavior: "collapse"
    use_saved_state: true
    sort_fn: "(a,b)=>{if((!a.isFolder&&!b.isFolder)||(a.isFolder&&b.isFolder)){return a.displayName.localeCompare(b.displayName,undefined,{numeric:true,sensitivity:'base'});}if(!a.isFolder&&b.isFolder){return 1;}else{return -1;}}"
    filter_fn: "(node)=>node.slugSegment!=='tags'"
    map_fn: "(node)=>node"
    order:
      - "filter"
      - "map"
      - "sort"

server:
  host: 0.0.0.0
  port: 40075
  max_payload_mb: 100
  cors_origins:
    - 0.0.0.0:40075

paths:
  content_root: ../content/
  cache_root: ../.build/
